[browser]
gatherUsageStats = false

[server]
address = "127.0.0.1"
headless = true

[theme]
base = "light"
primaryColor = "#236B58"
backgroundColor = "#F6F8F7"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1D3430"
baseRadius = "medium"
